name: BossbarCompass
main: me.compass.Brain
version: 0.0.1
api-version: 1.20
author: VisherRyz
description: See the edges of the world
commands:
    compass:
        description: Toogle compass
        usage: Use /<command>
    bc:
        description: Toogle compass
        usage: Use /<command>